services:
  db:
    image: postgres:13
    container_name: your_postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - flask_network

  app:
    build: .
    container_name: flask_app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - flask_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:

networks:
  flask_network:
